### PR TITLE
add missing lodash imports

### PR DESCRIPTION
**Pull request by mreinstein**
my project uses inspire-tree-dom but does not use lodash. This PR should make inspire-tree-dom work within my project without having to explicitly require lodash.

### CODE REVIEW

**Comment by mreinstein** [comment]
fixes #26

**Comment by viveleroi** [comment]
I assume so, but these were the only source files missing the imports, correct? I was under the impression there was a lint rule to catch these but apparently not...

**Comment by mreinstein** [comment]
I looked through `src/`, these were the only offenders I found.

**Comment by mreinstein** [comment]
thanks for merging! Can you submit a new npm release including this please?

**Comment by viveleroi** [comment]
Done, 4.0.6 is out.

**Pull request merged**
